### ISSUE TITLE
Crash on quitting when trying to Generate Import files

### ISSUE THREAD

**Issue by prculley** [corb555/GeoFinder#8]
**Describe the bug**
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.6\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\msys64\mingw64\lib\python3.6\site-packages\geofinder\GeoFinder.py", line 682, in quit_handler
    self.handle_place_entry()
  File "C:\msys64\mingw64\lib\python3.6\site-packages\geofinder\GeoFinder.py", line 325, in handle_place_entry
    self.end_of_file_shutdown()
  File "C:\msys64\mingw64\lib\python3.6\site-packages\geofinder\GeoFinder.py", line 842, in end_of_file_shutdown
    os.remove(f"{path}.{self.out_suffix}")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/Users/prc/workspace/Gramps2/works_2019-11-03.gramps.import.gramps'

**To Reproduce**
1.  Open and work on file
2. quit
3. Say yes to Generate Import File

OS: Win10

**Comment by corb555** [comment]
this should be fixed now in 0.8.6
